name: Release Workflow

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore VeeamHealthCheck.csproj
      working-directory: vHC/HC_Reporting

    - name: Build
      run: dotnet build VeeamHealthCheck.csproj --configuration Release --no-restore
      working-directory: vHC/HC_Reporting

    - name: Run tests
      run: dotnet test VeeamHealthCheck.csproj --no-restore --verbosity normal
      working-directory: vHC/HC_Reporting

    - name: Code scan
      uses: github/codeql-action/init@v1
      with:
        languages: csharp

    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v2



  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Publish project
      run: dotnet publish VeeamHealthCheck.csproj -c Release -o ./publish
      working-directory: vHC/HC_Reporting

    - name: Zip published files
      run: |
        $version = (Get-Command D:\a\veeam-healthcheck\veeam-healthcheck\vHC\HC_Reporting\publish\VeeamHealthCheck.exe).FileVersionInfo.FileVersion
        Write-Host("Version: $version")
        Compress-Archive -Path D:\a\veeam-healthcheck\veeam-healthcheck\vHC\HC_Reporting\publish\* -DestinationPath ./VeeamHealthCheck-$version.zip
      shell: pwsh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./VeeamHealthCheck-$version.zip
        asset_name: VeeamHealthCheck-*.zip
        asset_content_type: application/zip